flags: {}
packages:
- chart/
- chart-cairo/
- chart-diagrams/
- chart-tests/
- chart-gtk/
- chart-gtk3/
#flags:
#  gtk:
#    # This needs to be true on osx
#    have-quartz-gtk: false
resolver: lts-20.23
extra-deps:
- gtk-0.15.8
- gtk3-0.15.8
- gio-0.13.8.2
nix:
  packages: [pkgconfig, cairo, zlib, pango, xorg.xproto, xorg.libX11, gtk2, gtk3]